[build]
  base = "."  # Specify the root directory of your project
  publish = "build"  # Specify the directory where your built files are located
  command = "npm run build"  # Specify the build command

[build.environment]
  NODE_VERSION = "14"  # Specify the Node.js version used for the build

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
